# Form implementation generated from reading ui file '/home/jac4806/Documentos/Trader/PyTrader/F_Trader_4.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


